[gcp_service_account]
type = "service_account"
project_id = "dashboard-mockrun-7"
private_key_id = "32e99c61b68580317d6146e36961a331295bb398"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChIRygMjSc6L0j
dJSeGSZkEt535zVXsKbuIs+xz1pE36MnrKx6Rxo2CoXM96LkJqHtB6n5yFHPaC3Z
q2+xAtN455hapOsUKkShkuKLbyO0ucHuoqtMM/jW/SfZdwVmMsf+3Oa+sgK080Dr
BJYnAmdsdB1AHvhs3VJzqi7Z/Yg2BRt2k8EV29Zw6sXwbUtBnEevXrDWIk7s9Dm8
CVwHNafRFSiXRYAgjfeA9kbL6eQZ4jPpC0vV0pyKrIedl7vyxIE1y25dEbACaVbf
QwkQgKZXYD+AACVIb/jyfWnkp7zdcAumaNQGI0W0EbaC1GtRn2/LDcJvDrY8xW3/
FlYlDFxnAgMBAAECggEABr1RBAC7/Qj3FrHC1AIO5J/gnxJ6qeca2sCpM0snzKDi
1ov9NhG3SCXHuiHTHGJJSS+WFBTyGkMsEWJMUt96MCDWJiRzxYbz3yMHrffBSvpI
erTIuXBxd6/LDoHqv38sQleQoM7m5UhJCAt/ERtwPACqhvFErtKeQKkQbWnFwr/O
31IBKPdv+w7XjAi6zyc3J1HRxAk/wjYxpR23ife4VRTMJDDHKLHSvPOUXypdlbbx
VZ0uXIvSWDTqRXrnDtJTnTjJgW9fWHjeryXNEsR5DW8IpoqOKRNp0TiKGvgRPnAR
gAyInAG4iSrs/QoT7nKRFmFHHUZgySqEaJslD1DCMQKBgQDfPQZVDOD5jvEwpMFf
S1UOKPHOgIqgpQ/6XtiWF1VQKeIInhUKtsXER4YIxCWNqeaBNDiAQ67zx0gGfT4p
tJkFs+0nRKlmr3KYxWhDDhlnmLRNOF4xYNEzzqWOrVDDoa+hECkPXCut/SVXV3sK
nguaKH648i4pjXAXysrvtAywMDQKBgQC4xq0EgYJNM/gR3tP2lQBLZ+0/7KPEEoOy
JgAvy7XXOTFxF8XLKCsFpwxg43Z+GhcOgzQ4wBHoHcA+Qn7gfetNOmgEBU+rslnG
8+SdY0Wt0Ai7CGN3K6XSV5XMnlnnoQNTmiGF7iXwILDZZq7LjxiSWiCWkpOiTUHb
KSGC8IvJQwKBgAo2SnHdkvUXmuT0xHvNgGiTauxdaPoMUvzLFfFXw+lU4Sgvwxqo
Xceq1fDUuDsQyKCkeOk1L22rchoJ5KwXvOBL6M9hDrbJ0941OZ3HqVXZ4HWf3H85
xJgwHda3CvjIDra5fIddWgotiGXEdLZ4Yn9zD49per0s2oDNuFcRTBSJAoGBAIon
emvZDXz982ghLGi85Zh73ychnxzWHwPPZ+pUrOR8DdyaQrhwkyJJ0XaL/CezCDRA
o4YfDgR4Yinq/ASMAagfmHARLI2a74dTCkcnV4zq8+wsDHqo9vX7qLRyXZRTjjIv
FwuVkWYmezRBk0X9+whKPP14IMyEaU4dRcIqasoTAoGBANa0CV67hSIYUhbdG8Zk
GzPIRvQaWGQyHGdRApoK4MSK219849hP1j3QEFPLy8gU5cCK3fGTCjQ2DXRxY+Q9
S2dZx0TCXoO08j/PBapoPHw36cqio14fL6iLM3WVy3QkDNRvv4qtva9NCBRLsAq4
BxXD6bknH+UG+hVyPz0E1QcE
-----END PRIVATE KEY-----"""
client_email = "sheet-access@dashboard-mockrun-7.iam.gserviceaccount.com"
client_id = "104778582700851527751"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheet-access%40dashboard-mockrun-7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
