gcp_service_account = """
{
  "type": "service_account",
  "project_id": "dashboard-mockrun-7",
  "private_key_id": "32e99c61b68580317d6146e36961a331295bb398",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANB...==\\n-----END PRIVATE KEY-----\\n",
  "client_email": "sheet-access@dashboard-mockrun-7.iam.gserviceaccount.com",
  "client_id": "104778582700851527751",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sheet-access%40dashboard-mockrun-7.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
